---
apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  name: "kubeflow-pipelines.tanzu.vmware.com.0.1.0"
spec:
  refName: kubeflow-pipelines.tanzu.vmware.com
  version: "0.1.0"
  releaseNotes: |
        Initial release of the Kubeflow Pipelines package
  template:
    spec:
      fetch:
      - imgpkgBundle:
          image: "ghcr.io/agapebondservant/kubeflow:0.1.0"
      template:
      - ytt:
          paths:
          - "config/"
      - kbld:
          paths:
          - ".imgpkg/images.yml"
          - "-"
      deploy:
      - kapp: {}
