#@ load("@ytt:data", "data")
---
apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: kfp-httpproxy
  namespace: kubeflow
spec:
  routes:
  - conditions:
    - prefix: /
    services:
    - name: ml-pipeline-ui
      port: 80
  virtualhost:
    fqdn: #@ data.values.full_url
