apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: kfp-httpproxy
spec:
  routes:
  - conditions:
    - prefix: /
    services:
    - name: scdf-server
      port: 80
  virtualhost:
    fqdn: kubeflow-pipelines.${DATA_E2E_BASE_URL}
