---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: REPLACE_KUBEFLOW_PIPELINES_NAMESPACE
  namespace: flux-system
spec:
  interval: 2m
  sourceRef:
    kind: GitRepository
    name: mlops-flux-system
  path: ./kubeflow-pipelines/2.1.0
  prune: true
  wait: true
  timeout: 10m0s