---
apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: kubeflow-pipelines-tap
  labels:
    apps.tanzu.vmware.com/workload-type: web
    app.kubernetes.io/part-of: kubeflow-pipelines-tap
  annotations:
    autoscaling.knative.dev/minScale: "1"
spec:
  params:
    - name: clusterBuilder
      value: full
  env:
    - name: BP_WEB_SERVER
      value: nginx
  source:
    git:
      url: https://github.com/agapebondservant/kubeflow-pipelines-accelerator.git
      ref:
        branch: main