apiVersion: data.packaging.carvel.dev/v1alpha1
kind: PackageMetadata
metadata:
  # This will be the name of our package
  name: kubeflow-pipelines.tanzu.vmware.com
spec:
  displayName: "Kubeflow Pipelines"
  longDescription: "Kubeflow Pipelines deployment"
  shortDescription: "Kubeflow Pipelines deployment"
  categories:
  - ML
  - AI
  - MLOps
