apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: kubeflow-pipelines-httpproxy
  namespace: REPLACE_KUBEFLOW_PIPELINES_NAMESPACE
spec:
  routes:
    - conditions:
        - prefix: /
      services:
        - name: ml-pipeline-ui
          port: 80
  virtualhost:
    fqdn: REPLACE_KUBEFLOW_PIPELINES_FQDN